#!/bin/bash

# Package list comparator for OpenMandriva
# This script compares your original package list (packages_original.txt) with a clean OMLx-ROME install
# (OM_clean_packages.txt) to create a clean packages.txt file for installation

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

print_header() {
    echo -e "${BLUE}========================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}========================================${NC}"
}

print_section() {
    echo -e "\n${CYAN}--- $1 ---${NC}"
}

# Check if required files exist
if [[ ! -f "packages_original.txt" ]]; then
    echo -e "${RED}Error: packages_original.txt not found!${NC}"
    echo "This should contain your original package list to be analyzed."
    echo "Create this file with the packages you want to install."
    exit 1
fi

if [[ ! -f "OM_clean_packages.txt" ]]; then
    echo -e "${RED}Error: OM_clean_packages.txt not found!${NC}"
    echo "This should contain the package list from a clean OMLx-ROME install."
    exit 1
fi

print_header "OpenMandriva Package List Analyzer"

# Extract package names from original list (remove version info)
echo -e "${YELLOW}Processing your original package list (packages_original.txt)...${NC}"
grep -v '^[[:space:]]*$' packages_original.txt | \
awk '{print $1}' | \
sed 's/-[0-9].*//' | \
sort -u > /tmp/original_packages_clean.txt

original_count=$(wc -l < /tmp/original_packages_clean.txt)
echo -e "${GREEN}Found $original_count packages in your original list${NC}"

# Extract package names from clean install (remove version info)
echo -e "${YELLOW}Processing clean install packages (OM_clean_packages.txt)...${NC}"
grep -v '^[[:space:]]*$' OM_clean_packages.txt | \
awk '{print $1}' | \
sed 's/-[0-9].*//' | \
sort -u > /tmp/clean_packages_clean.txt

clean_count=$(wc -l < /tmp/clean_packages_clean.txt)
echo -e "${GREEN}Found $clean_count packages in clean install${NC}"

print_section "Comparing Package Lists"

# Find packages that are only in your original list (not in clean install)
comm -23 /tmp/original_packages_clean.txt /tmp/clean_packages_clean.txt > /tmp/custom_packages.txt

# Find packages that are in both (will be excluded)
comm -12 /tmp/original_packages_clean.txt /tmp/clean_packages_clean.txt > /tmp/common_packages.txt

custom_count=$(wc -l < /tmp/custom_packages.txt)
common_count=$(wc -l < /tmp/common_packages.txt)

# Display results
print_section "Packages Already in Clean Install (will be excluded)"
echo -e "${YELLOW}Count: $common_count${NC}"
if [[ $common_count -gt 0 ]]; then
    echo -e "${CYAN}These packages are already present in clean OMLx-ROME install:${NC}"
    if [[ $common_count -le 20 ]]; then
        cat /tmp/common_packages.txt
    else
        head -20 /tmp/common_packages.txt
        echo "... and $((common_count - 20)) more"
    fi
fi

print_section "Packages to Install (your custom selections)"
echo -e "${GREEN}Count: $custom_count${NC}"
if [[ $custom_count -gt 0 ]]; then
    echo -e "${CYAN}These packages will be installed (not in clean install):${NC}"
    sort /tmp/custom_packages.txt
else
    echo -e "${YELLOW}No packages to install found!${NC}"
fi

# Create clean package list for installation
print_section "Creating Clean Package List for Installation"
{
    echo "# OpenMandriva Package List for Installation"
    echo "# Generated by package analyzer on $(date)"
    echo "# Contains only packages that need to be installed"
    echo "# (Packages already in clean OMLx-ROME install have been excluded)"
    echo ""
    echo "# Source files:"
    echo "#   Original list:    packages_original.txt"
    echo "#   Clean install:    OM_clean_packages.txt"
    echo "#   Output:           packages.txt (ready for OMLx_install.sh)"
    echo ""
    if [[ -s /tmp/custom_packages.txt ]]; then
        sort /tmp/custom_packages.txt
    else
        echo "# No packages to install found"
    fi
} > packages.txt

print_header "Analysis Complete"
echo -e "${GREEN}Clean package list created: packages.txt${NC}"
echo -e "${YELLOW}Original packages: $original_count${NC}"
echo -e "${YELLOW}Clean install packages: $clean_count${NC}"
echo -e "${YELLOW}Common packages (excluded): $common_count${NC}"
echo -e "${GREEN}Packages to install: $custom_count${NC}"

if [[ $custom_count -gt 0 ]]; then
    reduction_percent=$(( (common_count * 100) / original_count ))
    echo -e "\n${CYAN}Optimization: $common_count packages excluded (already in clean install)${NC}"
    echo -e "${CYAN}Efficiency: ~${reduction_percent}% reduction in package list${NC}"
    echo -e "${GREEN}Ready to run: OMLx_install.sh will use this packages.txt file${NC}"
else
    echo -e "\n${YELLOW}All your packages are already in the clean install!${NC}"
    echo -e "${YELLOW}No installation needed.${NC}"
fi

# Cleanup
rm -f /tmp/original_packages_clean.txt /tmp/clean_packages_clean.txt /tmp/custom_packages.txt /tmp/common_packages.txt

if [[ $custom_count -gt 0 ]]; then
    echo -e "\n${GREEN}✅ packages.txt created successfully!${NC}"
    echo -e "${GREEN}🚀 You can now run: bash OMLx_install.sh${NC}"
else
    echo -e "\n${YELLOW}⚠ No packages.txt created (nothing to install)${NC}"
fi
